In [18]:
#Task1:1 Exception handling

def division(x):
    try:
         x=5/0
    except:
        print("number can not be divide by zero")
division('x')

number can not be divide by zero


In [12]:
#Task1:2

subject=["Americans","Indians"]
verb=["Play","Watch"]
object=["Baseball","Cricket"]
sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in object]
for sentence in sentence_list:
    print (sentence)

Americans Play Baseball
Americans Play Cricket
Americans Watch Baseball
Americans Watch Cricket
Indians Play Baseball
Indians Play Cricket
Indians Watch Baseball
Indians Watch Cricket


In [23]:
#Task2:Matrix are powers of the input vector

import numpy as np
def gen_vander_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx

inputvector = np.array([1,2,3,4,])
no_col_opmat = 3
op_matx_dec_order = gen_vander_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = gen_vander_matrix(inputvector,no_col_opmat,True)
print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")

The input array is: [1 2 3 4] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]] 

